### ISSUE TITLE
There are tags in hex.pm, but no tags for the git repo, why?

### ISSUE THREAD

**Issue by getong** [lasp-lang/partisan#185]

**Comment by cmeiklejohn** [comment]
I haven't been the one pushing or building the hex package, @tsloughter has.

**Comment by getong** [comment]
Is it possible to make tags on git repo?

**Comment by cmeiklejohn** [comment]
There's nothing preventing us from doing it, I just think we've haven't done it because we've forgotten.  We can do it moving forward, but it's going to be impossible to go back and figure out what packages map to which commits -- or rather -- it's something that I don't have time for, nor know how to do.

**Comment by getong** [comment]
The latest tag in hex.pm.is 2.1.0, we can add new tags bigger than it.

**Comment by cmeiklejohn** [comment]
We can begin making tags moving forward.
